/*
 * Source code in 3rd-party is licensed and owned by their respective
 * copyright holders.
 *
 * All other source code is copyright Tresys Technology and licensed as below.
 *
 * Copyright (c) 2012 Tresys Technology LLC, Columbia, Maryland, USA
 *
 * This software was developed by Tresys Technology LLC
 * with U.S. Government sponsorship.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tresys.jalop.jnl;

import java.net.InetAddress;

/**
 * This event is generated by a {@link Context} and delivered to the registered
 * {@link ConnectionHandler} when a JALoP Session is established with another
 * JALoP Network Store.
 * 
 * @see ConnectionHandler#connectAck(Session, ConnectAck)
 */
public interface ConnectAck {
	/**
	 * Retrieve the address of the connection remote JALoP Network Store.
	 * 
	 * @return The IPv4 or IPv6 address of the remote.
	 */
	InetAddress getAddress();

	/**
	 * Retrieve the version of JALoP that is used for the connection.
	 * 
	 * @return The JALoP version number.
	 */
	int getJalopVersion();

	/**
	 * Retrieve the jalop-agent (if any was specified) of the remote JALoP
	 * Network Store.
	 * 
	 * @return The JALoP user agent.
	 */
	String getJalopAgent();

	/**
	 * Retrieve the established role (Publisher or Subscriber).
	 * 
	 * @return The {@link Role}.
	 */
	Role getRole();

	/**
	 * Retrieve any MIME headers that were sent as part of the connect message.
	 * 
	 * @return The {@link MimeHeaders}
	 */
	MimeHeaders getHeaders();
}
